server:
  port: 9091
  compression:
    enabled: true
    mime-type: application/json,application/xml,text/html,text/xml,text/plain
spring:
  application:
    name: service-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true  #是否需要注册
  redis:
    timeout: 10000
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 1024  #最大连接数
        max-wait: 10000   #最大连接阻塞等待时间
        max-idle: 200     #最大空闲连接
        min-idle: 5       #最小空闲连接
feign:
  httpclient:
    enabled: true
